version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test12Project
  gitServerName: rihui
  gitUrl: https://github.com/Rihui-L-IBM
  gitUsername: Rihui-L-IBM
  gitBranch: main
- name: JcPublicTools
  wpmServer: https://packages.webmethods.io
  wpmRegistry: public
  wpmVersion: v2.1.0
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
  wpmVersion: v10.3.10.25
